CREATE TABLE `purchases` (
	`id` varchar(64) NOT NULL,
	`timestamp` timestamp NOT NULL DEFAULT (now()),
	`hubVendorId` varchar(64) NOT NULL,
	`hubVendorName` varchar(255) NOT NULL,
	`spokeIntegrationId` varchar(64) NOT NULL,
	`spokeIntegrationName` varchar(255) NOT NULL,
	`customerName` varchar(255) NOT NULL,
	`customerEmail` varchar(320) NOT NULL,
	`selectedDataTypes` text,
	`otherDataTypes` text,
	`companyName` varchar(255),
	`entityType` varchar(64),
	`syncFrequency` varchar(64),
	`dataVolume` varchar(64),
	`pricingTier` varchar(64),
	`selectedPlan` varchar(64),
	`additionalNotes` text,
	`termsAccepted` varchar(10) NOT NULL DEFAULT 'false',
	`termsAcceptedAt` timestamp,
	`stripeSessionId` varchar(255),
	`paymentStatus` enum('pending','completed','failed') NOT NULL DEFAULT 'pending',
	`paymentAmount` varchar(20),
	`paymentCurrency` varchar(10) DEFAULT 'USD',
	`paidAt` timestamp,
	`templateId` varchar(64) NOT NULL,
	`notificationEmailSent` varchar(10) DEFAULT 'false',
	`logFilePath` varchar(512),
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()),
	CONSTRAINT `purchases_id` PRIMARY KEY(`id`)
);
